### ISSUE TITLE
Wrong year when creating literature notes with template

### ISSUE THREAD

**Issue by phlind** [hans/obsidian-citation-plugin#40]
When a new literature note is created, 1 is subtracted from the year of the entry. So, for example, if I create a literature note for an entry with the year 2000, the note contains: "year: 1999". I checked this with several entries. I'm using CSL-JSON.

**Comment by hans** [comment]
Hi, a bug that caused the same issue was fixed in the 0.3.4 release. Can
you confirm that you are using 0.3.4?

If you are -- would you mind sharing your CSL export here so that I can
reproduce the issue on my end?

**Comment by phlind** [comment]
Yes, I'm using version 0.3.4. I converted my JSON from a BIB file with pandoc-citeproc. Here ist the file:
[biblio.json.zip](https://github.com/hans/obsidian-citation-plugin/files/5796142/biblio.json.zip)

**Comment by hans** [comment]
Hmm, this is very strange — I'm not able to reproduce that issue with your bibliography, and not on version 0.3.2, 0.3.3, or 0.3.4.
Which entries in particular cause this problem for you?

(Worked fine for me with `Lanfraconi2000` and `Heller1972`.)

**Comment by phlind** [comment]
The problem occurs for every entry I've tried, also for the ones you mentioned.

**Comment by phlind** [comment]
Do you maybe have a hint to what caused the bug, so I can try to investigate it further? @hans

**Comment by phlind** [comment]
I now found that the problem always occurs when the date only contains the year. @hans 

So it's working fine when an entry has:

```
"date-parts": [
        [
          2012,
          12
        ]
      ]
```

...whereas the error (-1) is produced, when it looks like this:

```
"date-parts": [
        [
          2012,
          12
        ]
      ]
```

**Comment by hans** [comment]
Hmm, this is exactly the bug that was fixed in the 0.3.4 release. Let me try and see if I can reproduce it on Windows -- it seems plausible that the bug might have some extra complications there.

Thanks a lot for your patience!

**Comment by phlind** [comment]
@hans Sorry, I mean to say that I have the problem on macOS and also on Windows. I just used Windows to see if it's also there.

**Comment by TeresaM12** [comment]
I have the same problem with plugin version 0.4.1, obsidian version 0.10.13 also on a Win and on a Mac computer and only if for the date is only the year set. Json file is still correct.
`"issued":{"date-parts":[[2020]]}` results in  `year: 2019`

But if I understand correctly you try to solve this in 0.4.2. Thanks for the effort

**Comment by valmaev** [comment]
For those who don't want to wait the PR approval and the next release of the plugin:

1. Navigate to `{your-vault}/.obsidian/plugins/obsidian-citation-plugin/` folder.
2. Open `main.js` in your favorite editor.
3. Find the line `return new Date(year, (month || 1) - 1, day || 1);` (in my case it was on the 49677 line).
4. Replace it with `return new Date(Date.UTC(year, (month || 1) - 1, day || 1));`
5. Restart Obsidian.

**Comment by gcarlet** [comment]
Still have the same problem with plugin version 0.4.4 obsidian version 0.13.23  on a Mac

**Comment by zchap26** [comment]
Issue persists with plugin version 0.4.4 and Obsidian 0.14.15 on Linux.

Regards

**Comment by xl0** [comment]
@hans, any chance you could pull the changes?
As I understand, the issue will only affect people in time zones ahead of UTC.
